### ISSUE TITLE
installed in Libreelec but seem to be missing six ? 

### ISSUE THREAD

**Issue by jasonblewis** [marcelveldt/plugin.audio.spotify#141]
I've installed the addon in libreelec but I see this error in the logs when I run the addon:

```
2020-03-22 22:13:47.982 T:1937481248   ERROR: Control 55 in window 10502 has been asked to focus, but it can't
2020-03-22 22:13:48.706 T:1398014832   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named six
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.spotify/plugin.py", line 11, in <module>
                                                from plugin_content import PluginContent
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 9, in <module>
                                                import spotipy
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/spotipy/__init__.py", line 2, in <module>
                                                from .client import Spotify, SpotifyException
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/spotipy/client.py", line 10, in <module>
                                                import six
                                            ImportError: No module named six
                                            -->End of Python script error report<--
2020-03-22 22:13:48.746 T:1406407536   ERROR: GetDirectory - Error getting plugin://plugin.audio.spotify/
2020-03-22 22:13:48.746 T:1937481248   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.spotify/) failed

```
Any ideas how to resolve this issue?

**Comment by jasonblewis** [comment]
this was with version 1.1.59
