### ISSUE TITLE
Spotify can't install

### ISSUE THREAD

**Issue by NickMous** [marcelveldt/plugin.audio.spotify#142]
Every time when I install Spotify, it doesn't install because it failed. Don't know why it fails, but maybe because LibreELEC got a new update to Kodi Leia.
Maybe that you guys can do anything with it?

**Comment by joazif** [comment]
Hi, I have the same problem.

Log: 

2020-04-16 09:16:24.377 T:2650289008 WARNING: Previous line repeats 7 times.

2020-04-16 09:16:24.377 T:2650289008   ERROR: Requested path https://raw.githubusercontent.com/marcelveldt/repository.marcelveldt/master/script.module.cherrypy/script.module.cherrypy-11.0.1.zip not found in known repository directories

2020-04-16 09:16:24.377 T:2650289008   ERROR: CAddonInstallJob[script.module.cherrypy]: failed to resolve addon install source path

2020-04-16 09:16:24.380 T:2650289008   ERROR: CAddonInstallJob[plugin.audio.spotify]: failed to install dependency script.module.cherrypy


Raspberry Pi 4B,  LibreELEC 9.2.1

**Comment by thiagocavalcanti** [comment]
I had to install the dependencies one by one. Some of them, i install using the kodi oficial repo and then I could install the spotify lib

**Comment by quentinravet** [comment]
[repository.marcelveldt-1.0.2.zip](https://github.com/kodi-community-addons/plugin.audio.spotify/files/4543943/repository.marcelveldt-1.0.2.zip)

You can find here the new repo, the 1.0.1 is not working anymore for me

**Comment by ghost** [comment]
> [repository.marcelveldt-1.0.2.zip](https://github.com/kodi-community-addons/plugin.audio.spotify/files/4543943/repository.marcelveldt-1.0.2.zip)
> 
> You can find here the new repo, the 1.0.1 is not working anymore for me

I'm also having no luck using 1.0.2. Install works for you?

**Comment by hummuscience** [comment]
I am on LibreELEC running Kodi 18

Downloading the .zip file and installing from repository fails as the dependencies are missing (for example CherryPy). And some of them cannot be installed, not even manually.

I then downloaded the master form the repo, unzipped and moved it to the `~/.kodi/addons `folder, restarted and then I was able to "enable" the plugin. 

Added my credentials etc. but got an error when I go onto the Addon.

Checked the logs and it seems to hang because cherrypy is missing.

```
020-04-29 15:25:17.733 T:3011338256 WARNING: CAddonMgr: 'script.module.simplejson' required by 'plugin.audio.spotify' is missing. Add-on may not function correctly
2020-04-29 15:25:17.733 T:3011338256 WARNING: CAddonMgr: 'script.module.simplecache' required by 'plugin.audio.spotify' is missing. Add-on may not function correctly
2020-04-29 15:25:17.733 T:3011338256 WARNING: CAddonMgr: 'script.module.cherrypy' required by 'plugin.audio.spotify' is missing. Add-on may not function correctly
2020-04-29 15:25:17.733 T:3011338256 WARNING: CAddonMgr: 'script.module.metadatautils' required by 'plugin.audio.spotify' is missing. Add-on may not function correctly
2020-04-29 15:25:17.752 T:3011338256   DEBUG: CAddonMgr: enabled plugin.audio.spotify
2020-04-29 15:25:17.753 T:2609869680   DEBUG: Thread JobWorker start, auto delete: true
2020-04-29 15:25:17.793 T:2609869680   DEBUG: CServiceAddonManager: starting plugin.audio.spotify
2020-04-29 15:25:17.794 T:2858812272   DEBUG: Thread LanguageInvoker start, auto delete: false
2020-04-29 15:25:17.794 T:2858812272    INFO: initializing python engine.
2020-04-29 15:25:17.795 T:2858812272   DEBUG: CPythonInvoker(3, /storage/.kodi/addons/plugin.audio.spotify/service.py): start processing
2020-04-29 15:25:17.851 T:2858812272   DEBUG: -->Python Interpreter Initialized<--
2020-04-29 15:25:17.851 T:2858812272   DEBUG: CPythonInvoker(3, /storage/.kodi/addons/plugin.audio.spotify/service.py): the source file to load is "/storage/.kodi/addons/plugin.audio.spotify/service.py"
2020-04-29 15:25:17.853 T:2858812272   DEBUG: CPythonInvoker(3, /storage/.kodi/addons/plugin.audio.spotify/service.py): setting the Python path to /storage/.kodi/addons/plugin.audio.spotify:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
2020-04-29 15:25:17.854 T:2858812272   DEBUG: CPythonInvoker(3, /storage/.kodi/addons/plugin.audio.spotify/service.py): entering source directory /storage/.kodi/addons/plugin.audio.spotify
2020-04-29 15:25:17.854 T:2858812272   DEBUG: CPythonInvoker(3, /storage/.kodi/addons/plugin.audio.spotify/service.py): instantiating addon using automatically obtained id of "plugin.audio.spotify" dependent on version 2.1.0 of the xbmc.python api
2020-04-29 15:25:17.884 T:3011338256   DEBUG: CGUIMediaWindow::GetDirectory (addons://user/all)
2020-04-29 15:25:17.884 T:3011338256   DEBUG:   ParentPath = [addons://user/all]
2020-04-29 15:25:17.885 T:2601476976   DEBUG: Thread waiting start, auto delete: false
2020-04-29 15:25:17.920 T:2601476976   DEBUG: CAddonMgr::GetAvailableUpdates took 24 ms
2020-04-29 15:25:17.929 T:2601476976   DEBUG: Thread waiting 2601476976 terminating
2020-04-29 15:25:17.937 T:2601476976   DEBUG: Thread BackgroundLoader start, auto delete: false
2020-04-29 15:25:17.943 T:2609869680   DEBUG: GetImageHash - unable to stat url /storage/.kodi/addons/inputstream.adaptive/icon.png
2020-04-29 15:25:17.951 T:2601476976   DEBUG: Thread BackgroundLoader 2601476976 terminating
2020-04-29 15:25:18.310 T:2858812272   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named cherrypy
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.spotify/service.py", line 13, in <module>
                                                from main_service import MainService
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 14, in <module>
                                                from httpproxy import ProxyRunner
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/httpproxy.py", line 7, in <module>
                                                import cherrypy
                                            ImportError: No module named cherrypy
                                            -->End of Python script error report<--
2020-04-29 15:25:18.310 T:2858812272   DEBUG: onExecutionDone(3, /storage/.kodi/addons/plugin.audio.spotify/service.py)
2020-04-29 15:25:18.314 T:3011338256   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-04-29 15:25:18.319 T:2858812272    INFO: Python interpreter stopped
2020-04-29 15:25:18.319 T:2858812272   DEBUG: Thread LanguageInvoker 2858812272 terminating
```

**Comment by hummuscience** [comment]
A complete fresh install of LibreELEC fixed the issue

**Comment by xcarol** [comment]
> [repository.marcelveldt-1.0.2.zip](https://github.com/kodi-community-addons/plugin.audio.spotify/files/4543943/repository.marcelveldt-1.0.2.zip)
> 
> You can find here the new repo, the 1.0.1 is not working anymore for me

It worked for me. Thanks!

If I can help any of you to find repo/component versions, or whatever, just let me know!

**Comment by jveitchmichaelis** [comment]
I got it working by also installing CherryPy manually. The addon also doesn't prompt for username when it loads, so you need to update the settings manually.

https://github.com/kodi-community-addons/script.module.cherrypy

**Comment by djtale** [comment]
Hello,

I'm using Recalbox 7.0 on my RPi4.
I am installing the Spotify plugin 1.1.58 from the Marcelveldt repository 1.0.2
I noticed my cherryPy Kodi module is in version 17.4.0 (no idea if that is useful to mention).

The plugin is installed.
Right after the install I get this error in the log :
`2020-10-05 18:58:57.467 T:2610951072 WARNING: CAddonMgr: 'script.module.certifi' required by 'plugin.audio.spotify' is missing. Add-on may not function correctly
2020-10-05 18:58:59.504 T:1682957216 WARNING: plugin.audio.spotify --> Exception in utils ! --> [Errno 13] Permission denied
2020-10-05 18:58:59.845 T:1682957216 WARNING: Previous line repeats 3 times.
2020-10-05 18:58:59.845 T:1682957216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'Bus' object has no attribute 'timeout_monitor'
                                            Traceback (most recent call last):
                                              File "/recalbox/share/system/.kodi/addons/plugin.audio.spotify/service.py", line 14, in <module>
                                                MainService()
                                              File "/recalbox/share/system/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 54, in __init__
                                                self.proxy_runner = ProxyRunner(self.spotty)
                                              File "/recalbox/share/system/.kodi/addons/plugin.audio.spotify/resources/lib/httpproxy.py", line 218, in __init__
                                                'server.shutdown_timeout': 1
                                              File "/recalbox/share/system/.kodi/addons/script.module.cherrypy/lib/cherrypy/_cpconfig.py", line 157, in update
                                                super(Config, self).update(config)
                                              File "/recalbox/share/system/.kodi/addons/script.module.cherrypy/lib/cherrypy/lib/reprconf.py", line 130, in update
                                                self._apply(Parser.load(config))
                                              File "/recalbox/share/system/.kodi/addons/script.module.cherrypy/lib/cherrypy/_cpconfig.py", line 167, in _apply
                                                super(Config, self)._apply(config)
                                              File "/recalbox/share/system/.kodi/addons/script.module.cherrypy/lib/cherrypy/lib/reprconf.py", line 142, in _apply
                                                self.namespaces(config)
                                              File "/recalbox/share/system/.kodi/addons/script.module.cherrypy/lib/cherrypy/lib/reprconf.py", line 92, in __call__
                                                handler(k, v)
                                              File "/recalbox/share/system/.kodi/addons/script.module.cherrypy/lib/cherrypy/_cpconfig.py", line 270, in _engine_namespace_handler
                                                plugin = getattr(engine, plugin)
                                            AttributeError: 'Bus' object has no attribute 'timeout_monitor'
                                            -->End of Python script error report<--
`

When I open the plugin, I get this meessage :
"The default browser should now be opened, ...."

What could be the root cause to that ?

I have the BINGIE repository installed and CherryPy comes from that repository in version 17.4.0.

Thanks for your help.

**Comment by nisnevich** [comment]
> [repository.marcelveldt-1.0.2.zip](https://github.com/kodi-community-addons/plugin.audio.spotify/files/4543943/repository.marcelveldt-1.0.2.zip)
> 
> You can find here the new repo, the 1.0.1 is not working anymore for me

Thanks a lot! Works like a charm.

**Comment by Westiewombat** [comment]
Kodi install on Pi4 - Spotify fails due to CherryPy error but the only dependecy is Six which is installed. Tried manual CherryPy install as per above issue with xbmc.python dependency .. running out of ideas

**Comment by utomsig** [comment]
The problem with the installation of cherrypy is still there for me, even with the repository.marcelveldt-1.0.2.zip. I run a raspberry pi 3, Raspbian 10 with Kodi 18.7.
A workaround is to install [Librespot](https://github.com/librespot-org/librespotl) under whatever system u are running. Quickest way to get it running is to download a binary from [Spotifyd](https://github.com/Spotifyd/spotifyd/releases/l) You will not get an interface in Kodi, but u can control it through the official spotify-app on your phone. For the raspberry download the spotifyd-linux-armhf-default.tar.gz, e.g. 
```
mkdir -p /home/$USER/bin && cd /home/$USER/bin
wget "https://github.com/Spotifyd/spotifyd/releases/download/v0.3.2/spotifyd-linux-armhf-default.tar.gz"
```
but please change the link to the latest release. Then unpack it: 
`tar -xvf spotifyd-linux-default.tar.gz && rm spotifyd-linux-default.tar.gz`
To run it:
```
spotifyd --name Spotifyd --username YOURUSERAME --password YOURPASSWORD
```
and now you should be able to choose it from the spotify app on your phone!
To have it running on boot, check out this [link](https://github.com/librespot-org/librespot/wiki/Running-in-the-background).

**Comment by LoreneParsons** [comment]
You can install Spotify premium easily when you download Spotify on https://gamestoremobi.com/spotify-premium.html, I have installed and used Spotify for free for 1 year.

**Comment by yesmar12** [comment]
I installed the repository but when I open the repository in kodi it says "Could not connect to repository". I am very new to this so I'm not really sure whats wrong.

**Comment by yesmar12** [comment]
> I installed the repository but when I open the repository in kodi it says "Could not connect to repository". I am very new to this so I'm not really sure whats wrong.

Found a fix for this: [1.0.3](https://github.com/kodi-community-addons/repository.marcelveldt/raw/master/repository/repository.marcelveldt/repository.marcelveldt-1.0.3.zip) This is a newer zip that seems to be for the version of kodi I am using but not quite sure.

**Comment by HeatherRussell25** [comment]
This issue will be taken care of by our team. Thanks to the publisher for letting us know. This issue will be taken care of by our team. You can come here [modded apk for android](https://apkmodv.com/) to experience many good games.
