### ISSUE TITLE
Credentials error

### ISSUE THREAD

**Issue by og13270** [marcelveldt/plugin.audio.spotify#156]
Hi,
First of all, thanks for your job. I enjoyed this addon since i got this error. I used it on a rasberry 4.0/librelec 9.2.6./kodi 18.9 leia/spotify addon 1.1.58. I run spotify plugin and then a message box with credendtials or login error.  Here is the kodi.log lines about error 

2021-02-21 12:42:49.580 T:2711585648 WARNING: plugin.audio.spotify --> Exception in utils ! --> execv() arg 2 must contain only strings
2021-02-21 12:42:49.780 T:2711585648 WARNING: plugin.audio.spotify --> Exception in utils ! --> 'NoneType' object has no attribute 'communicate'
2021-02-21 12:42:54.856 T:2198766448   ERROR: Exception in thread Thread-4804:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/utils.py", line 110, in kill_on_timeout
                                                proc.kill()
                                            AttributeError: 'NoneType' object has no attribute 'kill'

**Comment by au5tr1ng3r** [comment]
Same issue. 

Btw, if I use Facebook as login, which credentials are to be put into the add-on?

I have a premium account
