### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Dialog'

### ISSUE THREAD

**Issue by nycholas** [marcelveldt/plugin.audio.spotify#22]
Hello,

*Kodi:* 17.1 Git:20170327-nogitfound Media Center Kodi
*plugin.audio.spotify:* master branch

I have a error when inicialize the plugin:

```
12:29:54.396 T:1371923344  NOTICE: LoadJpeg: unable to load /var/lib/kodi/.kodi/addons/plugin.audio.spotify/fanart.jpg
12:29:56.359 T:1806693264   ERROR: GetDirectory - Error getting
12:30:01.370 T:1557119888   ERROR: Previous line repeats 3 times.
12:30:01.370 T:1557119888  NOTICE: Spotify --> Your platform (armv7 System.Platform.Linux)
12:30:10.708 T:1557119888  NOTICE: Spotify --> Starting background service...
12:30:10.750 T:1557119888  NOTICE: Spotify --> Checking remembered_user ..
12:30:10.773 T:1557119888  NOTICE: Spotify --> Cached session found
12:30:10.780 T:1472586640  NOTICE: Spotify --> logged in: 0
12:30:15.937 T:1557119888  NOTICE: Spotify --> starting proxy at port 8090
12:30:15.938 T:1557119888  NOTICE: Spotify --> Setting callback ..
12:30:15.939 T:1557119888  NOTICE: Spotify --> Obtaining user token ..
12:30:15.941 T:1557119888  NOTICE: Spotify --> Encoding header ..
12:30:16.500 T:1505735568   ERROR: warning:couldn't read token from cache
12:30:16.501 T:1505735568  NOTICE: Spotify --> WebService - start helper webservice on port 52308
12:30:17.561 T:1505735568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'Dialog'
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.audio.spotify/plugin.py", line 3, in <module>
                                                Main().main()
                                              File "/var/lib/kodi/.kodi/addons/plugin.audio.spotify/resources/plugincontent.py", line 1146, in main
                                                if self.checkLoginDetails():
                                              File "/var/lib/kodi/.kodi/addons/plugin.audio.spotify/resources/plugincontent.py", line 1074, in checkLoginDetails
                                                self.token = util.prompt_for_user_token(username)
                                              File "/var/lib/kodi/.kodi/addons/plugin.audio.spotify/resources/libs/spotipy/util.py", line 69, in prompt_for_user_token
                                                if xbmc.Dialog().yesno("No webbrowser detected", "The webbrowser could not be auto detected. Do you have one installed ?"):
                                            AttributeError: 'module' object has no attribute 'Dialog'
                                            -->End of Python script error report<--
```

**Comment by marcelveldt** [comment]
please see the forum thread... you need to copy some files if you are running the plugin on a system without a webbrowser

**Comment by nycholas** [comment]
Yes, the problem is about Dialog attribute, after installed the webbrowser do work.

Thank you.
