### ISSUE TITLE
Cannot connect with creditentials

### ISSUE THREAD

**Issue by Satris404** [marcelveldt/plugin.audio.spotify#34]
Getting "No credentials have been set or the login failed.
Please enter your credentials in the next settings dialog."
 When trying to open the addon.  I'm using the version 1.1.29 on osmc, kodi 17.3. and tried both email and user id.

**Comment by marcelveldt** [comment]
Kodi logfile?

**Comment by mikk150** [comment]
I am getting the same error..
```
18:09:25.405 T:3663721456  NOTICE: plugin.audio.spotify --> reported architecture: aarch64
18:09:25.406 T:3663721456  NOTICE: plugin.audio.spotify --> Architecture detected. Using librespot binary /home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/librespot/linux_aarch64/librespot
18:09:25.424 T:3441456112  NOTICE: plugin.audio.spotify --> reported architecture: aarch64
18:09:25.425 T:3441456112  NOTICE: plugin.audio.spotify --> Architecture detected. Using librespot binary /home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/librespot/linux_aarch64/librespot
18:09:25.470 T:3663721456 WARNING: plugin.audio.spotify --> Exception in utils ! --> [Errno 2] No such file or directory
18:09:25.472 T:3663721456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'communicate'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/service.py", line 14, in <module>
                                                MainService()
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 40, in __init__
                                                self.librespot = LibreSpot()
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/utils.py", line 393, in __init__
                                                stdout, stderr = librespot.communicate()
                                            AttributeError: 'NoneType' object has no attribute 'communicate'
                                            -->End of Python script error report<--
18:09:25.707 T:3441456112 WARNING: plugin.audio.spotify --> Exception in utils ! --> [Errno 2] No such file or directory
18:09:25.708 T:3441456112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'communicate'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/service.py", line 14, in <module>
                                                MainService()
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 40, in __init__
                                                self.librespot = LibreSpot()
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/utils.py", line 393, in __init__
                                                stdout, stderr = librespot.communicate()
                                            AttributeError: 'NoneType' object has no attribute 'communicate'
                                            -->End of Python script error report<--
18:10:25.653 T:3729781744  NOTICE: ES: Client  from ::ffff:192.168.1.180 timed out
18:13:41.277 T:4112236544   ERROR: Control 55 in window 10502 has been asked to focus, but it can't

```

**Comment by Satris404** [comment]
11:30:28.694 T:1115419632  NOTICE: Previous line repeats 1 times.
11:30:28.694 T:1115419632 WARNING: Attempt to use invalid handle -1
11:31:44.825 T:1958555648 WARNING: Previous line repeats 2 times.
11:31:44.825 T:1958555648   ERROR: Control 53 in window 10001 has been asked to focus, but it can't
11:31:48.068 T:910504944   ERROR: Previous line repeats 1 times.
11:31:48.068 T:910504944 WARNING: Attempt to use invalid handle -1
11:32:39.790 T:1958555648 WARNING: Previous line repeats 2 times.
11:32:39.790 T:1958555648   ERROR: Control 53 in window 10001 has been asked to focus, but it can't

When I try to get into sportify, it only logs this in kodi.log (This is from trying 2 consecutive times to open up spotify)

**Comment by marcelveldt** [comment]
@mikk150 did you use some sort of path substitution for your kodi adding folder ? 

@Satris404 Did you install the add-on from my repo ?

**Comment by Satris404** [comment]
Yes, directly from your repo!

**Comment by Satris404** [comment]
Both of my raspberry pi have the same problem (one on OSMC and one on retropie). Am I doing something wrong? I put the same ID and password as if I was login into spotify.

**Comment by mikk150** [comment]
@marcelveldt I guess not considering that I have no idea what that means...

**Comment by Satris404** [comment]
@marcelveldt is thia could be because i'm from canada and my account is canadian?

**Comment by mikk150** [comment]
@marcelveldt seems like release 1.1.31 has fixed it

**Comment by marcelveldt** [comment]
@Satris404 did you test again with the latest release ? 1.1.36 should definitely fix it, also on OSMC.
