### ISSUE TITLE
Not playing songs on OSX

### ISSUE THREAD

**Issue by tit0n** [marcelveldt/plugin.audio.spotify#35]
Can see songs from my library, but nothing happen when i select a song to play....

```
00:34:03.597 T:4642906112   DEBUG: CPythonInvoker(27, /Users/xxx/Library/Application Support/Kodi/addons/plugin.audio.spotify/plugin.py): the source file to load is "/Users/xxx/Library/Application Support/Kodi/addons/plugin.audio.spotify/plugin.py"
00:34:03.597 T:4642906112   DEBUG: CPythonInvoker(27, /Users/xxx/Library/Application Support/Kodi/addons/plugin.audio.spotify/plugin.py): setting the Python path to /Users/xxx/Library/Application Support/Kodi/addons/plugin.audio.spotify:/Users/xxx/Library/Application Support/Kodi/addons/script.module.requests/lib:/Users/xxx/Library/Application Support/Kodi/addons/script.module.simplecache/lib:/Users/xxx/Library/Application Support/Kodi/addons/script.module.simplejson/lib:/Users/xxx/Library/Application Support/Kodi/addons/script.module.six/lib:/Users/xxx/Library/Application Support/Kodi/addons/script.module.unidecode/lib:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages/Pillow-3.0.0-py2.7-macosx-10.4-x86_64.egg:/Applications/Kodi.app/Contents/Libraries:/Applications/Kodi.app/Contents/Libraries/lib/python27.zip:/Applications/Kodi.app/Contents/Libraries/lib/python2.7:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/plat-darwin:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/plat-mac:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/plat-mac/lib-scriptpackages:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/lib-tk:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/lib-old:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/lib-dynload:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages
00:34:03.597 T:4642906112   DEBUG: CPythonInvoker(27, /Users/xxx/Library/Application Support/Kodi/addons/plugin.audio.spotify/plugin.py): entering source directory /Users/xxx/Library/Application Support/Kodi/addons/plugin.audio.spotify
00:34:03.597 T:4642906112   DEBUG: CPythonInvoker(27, /Users/xxx/Library/Application Support/Kodi/addons/plugin.audio.spotify/plugin.py): instantiating addon using automatically obtained id of "plugin.audio.spotify" dependent on version 2.1.0 of the xbmc.python api
00:34:03.759 T:4642906112   DEBUG: Skin Helper Simplecache --> Initialized
00:34:04.485 T:4642906112   DEBUG: plugin.audio.spotify --> Traceback (most recent call last):
                                              File "/Users/xxx/Library/Application Support/Kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 54, in __init__
                                                eval(action)()
                                              File "/Users/xxx/Library/Application Support/Kodi/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 219, in connect_playback
                                                if cur_playback["device"]["name"] != get_playername():
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
00:34:04.485 T:4642906112 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> 'NoneType' object has no attribute '__getitem__'
00:34:04.485 T:4642906112 WARNING: Attempt to use invalid handle -1
00:34:04.485 T:4642906112   DEBUG: Skin Helper Simplecache --> Closed
00:34:04.485 T:4642906112    INFO: CPythonInvoker(27, /Users/xxx/Library/Application Support/Kodi/addons/plugin.audio.spotify/plugin.py): script successfully run
00:34:04.498 T:4642906112    INFO: Python script stopped
```

**Comment by PiRXlv** [comment]
Same here with OSMC on Pi3.

Would be more than happy to debug further, but I'm not familiar enough with ecosystem to do it on my own.

**Comment by PiRXlv** [comment]
Did a little bit of a digging into that and seems that there is some issue with Spotify connect.

**Comment by marcelveldt** [comment]
Can you guys please test again with version 1.1.34 that is now available on my repo ?
If it still fails, report here on the forum but please provide a full Kodi logfile, not just a snippet.
