### ISSUE TITLE
Possible Kodi 16 Issues?

### ISSUE THREAD

**Issue by im85288** [marcelveldt/plugin.audio.spotify#4]
I switched to LibreElec using the official Jarvis v16.1 version but could not get the addon to load.

Looking at the logs I see:

`18:06:55 T:140258742540032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'error' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.spotify/plugin.py", line 3, in <module>
                                                Main().main()
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/plugincontent.py", line 1128, in main
                                                if self.checkLoginDetails():
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/plugincontent.py", line 1058, in checkLoginDetails
                                                xbmcgui.Dialog().ok(ADDON_NAME, ADDON.getLocalizedString(11019) + ': ' + error)
                                            UnboundLocalError: local variable 'error' `

Please let me know if I am doing something incorrectly. My spotify premium account works correctly and I have verified the username and password is correct in the addon config settings

**Comment by im85288** [comment]
Actually scrap this one, I needed to install the chromium browser to allow authorisation to work. Once I did that all working great :)
