### ISSUE TITLE
Local variable 'error' referenced before assignment

### ISSUE THREAD

**Issue by vando** [marcelveldt/plugin.audio.spotify#5]
I have this error message and I can't login on Spotify

```
05:39:45 308.158630 T:1685058464  NOTICE: Spotify --> waiting for service...
05:39:46 308.878510 T:1806693280  NOTICE: Spotify --> Your platform (armv7 System.Platform.Linux)
05:39:46 309.226440 T:1685058464  NOTICE: Spotify --> waiting for service...
05:39:47 309.650909 T:1806693280  NOTICE: Spotify --> Starting background service...
05:39:47 310.240234 T:1685058464  NOTICE: Spotify --> waiting for service...
05:39:48 310.440918 T:1806693280  NOTICE: Spotify --> Spotify Callbacks: 05:39:48.174 I [offline_authorizer.cpp:297] Unable to login offline: no such user
05:39:48 310.441925 T:1631789984  NOTICE: Spotify --> Spotify Callbacks: 05:39:48.177 I [ap:1752] Connecting to AP ap.spotify.com:4070
05:39:48 310.662781 T:1631789984  NOTICE: Spotify --> Spotify Callbacks: 05:39:48.398 I [ap:1226] Connected to AP: 23.92.108.98:4070
05:39:48 311.241425 T:1685058464  NOTICE: Spotify --> waiting for service...
05:39:50 312.803833 T:1631789984  NOTICE: Previous line repeats 1 times.
05:39:51 313.778229 T:1631789984  NOTICE: Spotify --> Spotify Callbacks: 05:39:50.539 E [ap:3915] Connection error:  410
05:39:51 313.779327 T:1685058464  NOTICE: Spotify --> waiting for service...
05:39:51 313.779663 T:1631789984   ERROR: None
05:39:51 313.830078 T:1590162336  NOTICE: Spotify --> logged in: 6
05:39:51 313.832275 T:1590162336  NOTICE: Spotify --> logged out
05:39:51 314.110260 T:1806693280  NOTICE: Spotify --> Background service stopped
05:39:52 314.788452 T:1685058464  NOTICE: Spotify --> waiting for service...
05:40:36 358.955566 T:1685058464  NOTICE: Previous line repeats 44 times.
05:40:36 358.955841 T:1685058464   ERROR: warning:couldn't read token from cache
05:40:36 358.956543 T:1685058464  NOTICE: Spotify --> WebService - start helper webservice on port 52308
05:40:38 360.559723 T:1685058464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'error' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.spotify-master/plugin.py", line 3, in <module>
                                                Main().main()
                                              File "/storage/.kodi/addons/plugin.audio.spotify-master/resources/plugincontent.py", line 1128, in main
                                                if self.checkLoginDetails():
                                              File "/storage/.kodi/addons/plugin.audio.spotify-master/resources/plugincontent.py", line 1058, in checkLoginDetails
                                                xbmcgui.Dialog().ok(ADDON_NAME, ADDON.getLocalizedString(11019) + ': ' + error)
                                            UnboundLocalError: local variable 'error' referenced before assignment
                                            -->End of Python script error report<--
```

Addon version: 1.0.19
OS: OpenELEC 6.95.3 (Kodi 16.1)
Hardware: Raspberry Pi 2

**Comment by marcelveldt** [comment]
This specific error should be fixed in version 1.0.20

Make sure to read about the workaround for Pi users

**Comment by markg85** [comment]
Hi,

I'm trying to run this plugin on kodi 17 and am using version 1.0.25. I'm getting the very same error Vando reported.
Just to be complete, the error i get:

```
14:10:44.020 T:139901185058560   ERROR: 127.0.0.1 - - [05/Mar/2017 14:10:44] "QUIT / HTTP/1.1" 200 -
14:10:44.350 T:139901668951808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'spotipy.oauth2.SpotifyOauthError'>
                                            Error Contents: Bad Request
                                            Traceback (most recent call last):
                                              File "/home/mark/.kodi/addons/plugin.audio.spotify/plugin.py", line 3, in <module>
                                                Main().main()
                                              File "/home/mark/.kodi/addons/plugin.audio.spotify/resources/plugincontent.py", line 1146, in main
                                                if self.checkLoginDetails():
                                              File "/home/mark/.kodi/addons/plugin.audio.spotify/resources/plugincontent.py", line 1074, in checkLoginDetails
                                                self.token = util.prompt_for_user_token(username)
                                              File "/home/mark/.kodi/addons/plugin.audio.spotify/resources/libs/spotipy/util.py", line 59, in prompt_for_user_token
                                                token_info = sp_oauth.get_access_token(code)
                                              File "/home/mark/.kodi/addons/plugin.audio.spotify/resources/libs/spotipy/oauth2.py", line 213, in get_access_token
                                                raise SpotifyOauthError(response.reason)
                                            SpotifyOauthError: Bad Request
                                            -->End of Python script error report<--

```
I havent tried the 1.0.26 version yet.

**Comment by mcortinas** [comment]
I've installed in OSMC and the 1.0.26 las has the same error
```09:50:03.589 T:1341121280  NOTICE: Spotify --> Starting background service...
09:50:04.421 T:1677718272   ERROR: GetDirectory - Error getting
09:50:04.479 T:1341121280   ERROR: Previous line repeats 3 times.
09:50:04.479 T:1341121280  NOTICE: Spotify --> Checking remembered_user ..
09:50:04.986 T:1694495488 WARNING: CSkinInfo: failed to load skin settings
09:50:10.315 T:1284985600  NOTICE: Spotify --> logged in: 0
09:50:14.828 T:1341121280  NOTICE: Spotify --> starting proxy at port 8090
09:50:14.829 T:1341121280  NOTICE: Spotify --> Setting callback ..
09:50:14.830 T:1341121280  NOTICE: Spotify --> Obtaining user token ..
09:50:14.831 T:1341121280  NOTICE: Spotify --> Encoding header ..
09:50:14.982 T:1466098432   ERROR: warning:couldn't read token from cache
09:50:14.996 T:1466098432  NOTICE: Spotify --> WebService - start helper webservice on port 52308
09:50:16.176 T:1466098432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'Dialog'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/plugin.py", line 3, in <module>
                                                Main().main()
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/plugincontent.py", line 1146, in main
                                                if self.checkLoginDetails():
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/plugincontent.py", line 1074, in checkLoginDetails
                                                self.token = util.prompt_for_user_token(username)
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/libs/spotipy/util.py", line 69, in prompt_for_user_token
                                                if xbmc.Dialog().yesno("No webbrowser detected", "The webbrowser could not be auto detected. Do you have one installed ?"):
                                            AttributeError: 'module' object has no attribute 'Dialog'
                                            -->End of Python script error report<--
```

**Comment by marcelveldt** [comment]
1.0.26 is a very old version which I don't support anymore. Please update to the latest version. Easiest is by installing my repo.

**Comment by mcortinas** [comment]
Great job! thank you @marcelveldt  it is work fine!
