### ISSUE TITLE
Can't login on RPi

### ISSUE THREAD

**Issue by franksny** [marcelveldt/plugin.audio.spotify#94]
I have a Rasberry Pi running OSMC. I have been using this addon for a year or so (thanks!) but about two weeks ago I started having problems to login. Tested same account on Windows x64 and works fine.

Kodi log shows this:
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.SyntaxError'>
Error Contents: unexpected EOF while parsing (<string>, line 0)
Traceback (most recent call last):
  File "/home/osmc/.kodi/addons/plugin.audio.spotify/service.py", line 14, in <module>
	MainService()
  File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 60, in __init__
	self.renew_token()
  File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 167, in renew_token
	username = self.get_username()
  File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 134, in get_username
	username = self.spotty.get_username()
  File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/utils.py", line 522, in get_username
	data = eval(data)
  File "<string>", line 0
	
	^
SyntaxError: unexpected EOF while parsing
-->End of Python script error report<--

**Comment by KarolisL** [comment]
I've also stumbled this issue. It's related to some nasty spotify authentication code (on this plugin's, not spotify end).

This is caused by an empty file, just delete it:
```sh
rm /home/osmc/.kodi/userdata/addon_data/plugin.audio.spotify/credentials.json
```

It should fix your problem.

**Comment by franksny** [comment]
Thanks! It works perfect now!
