### ISSUE TITLE
http status 404

### ISSUE THREAD

**Issue by fmonnot** [marcelveldt/plugin.audio.spotify#95]
Bonjour,
Je rencontre depuis peu une panne de l'addon spotify sous libreelec 8.2.5 / Kodi 17.6 (sous Raspberry PI)
Le plugin se lance, pas de soucis de connexion à spotify avec mon compte family.
Pas de soucis pour parcourir "ma musique", rechercher des playlist etc.
Par contre impossible de lancer la lecture d'un morceau de musique.
En regardant dans les log Kodi je vois les lignes suivantes 
----
10:02:36.491 T:1328542624 WARNING: Attempt to use invalid handle -1
10:02:36.515 T:1302328224 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play:
                                             No active device found
10:02:36.515 T:1302328224 WARNING: Attempt to use invalid handle -1
10:05:52.768 T:1760564128  NOTICE: plugin.audio.spotify --> Shutdown requested !
10:05:57.771 T:1945065936   ERROR: CPythonInvoker(0, /storage/.kodi/addons/plugin.audio.spotify/service.py): script didn't stop in 5 seconds - let's kill it
-----

En complément, la carte audio est une wifiberry, et fonctionne par ailleurs avec les addons youtube, la lecture de fichiers audio, les addons arte+7 etc.

Une idée ? (je suis pas expert et un peu a cours d'idées).
Merci d'avance
[01_KODI.log](https://github.com/marcelveldt/plugin.audio.spotify/files/2166740/01_KODI.log)

**Comment by fmonnot** [comment]
Perhaps with a English translation I will be more successful.
Sine a month now I have an error with Spotify Add-on.
My system is a Raspberry PI3 with LibreElec 8.2.5 / Kodi 17.5 (krypton) and a sound card HifiBerry with a RCA output.
PLugin is running, I can connect to Spotify (with a family account), I can browse playlists, "My Music" folder, search for music (I can see the search result) etc...
My problem is when I want to read a music. Nothing happens. (The file is not read).
When it failed  to read music I have this errors into kodi.log =

***
10:02:36.491 T:1328542624 WARNING: Attempt to use invalid handle -1
10:02:36.515 T:1302328224 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play:
No active device found
10:02:36.515 T:1302328224 WARNING: Attempt to use invalid handle -1
10:05:52.768 T:1760564128 NOTICE: plugin.audio.spotify --> Shutdown requested !
10:05:57.771 T:1945065936 ERROR: CPythonInvoker(0, /storage/.kodi/addons/plugin.audio.spotify/service.py): script didn't stop in 5 seconds - let's kill it
***

The full log is linked in the previous post. 

I don't really understand (there is a "No active device found" line, but I don't know about which device it talk. My soundCard HifiBerry is working find for all others plug-in or to watch films.

Thanks for your help.

Regards

**Comment by khobar** [comment]
Hi
Instead of opening I will hook up to this issue 
I seems to have similar plugin . 
I have 17.1 based kodi android , where I tried to install spotify plugin. All auth is correct ( all my lists are visible ) but when I try to play any song , there is brief loading and nothing happens

In logs I found similar thiing as @fmonnot 
`22:52:26.767 T:2097147576   DEBUG: plugin.audio.spotify --> Traceback (most recent call last):
                                              File "/mnt/internal_sd/Android/data/mygica.media.center/files/.mygica/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 54, in __init__
                                                eval(action)()
                                              File "/mnt/internal_sd/Android/data/mygica.media.center/files/.mygica/addons/plugin.audio.spotify/resources/lib/plugin_content.py", line 278, in connect_playback
                                                self.sp.start_playback(context_uri=context_uri, offset=offset)
                                              File "/mnt/internal_sd/Android/data/mygica.media.center/files/.mygica/addons/plugin.audio.spotify/resources/lib/spotipy/client.py", line 972, in start_playback
                                                return self._put(self._append_device_id("me/player/play", device_id), payload=data)
                                              File "/mnt/internal_sd/Android/data/mygica.media.center/files/.mygica/addons/plugin.audio.spotify/resources/lib/spotipy/client.py", line 190, in _put
                                                return self._internal_call('PUT', url, payload, kwargs)
                                              File "/mnt/internal_sd/Android/data/mygica.media.center/files/.mygica/addons/plugin.audio.spotify/resources/lib/spotipy/client.py", line 126, in _internal_call
                                                headers=r.headers)
                                            SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play:
                                             No active device found`
Full log ( debug msg I took is from line ~3k )
[mygica.log](https://github.com/marcelveldt/plugin.audio.spotify/files/2203410/mygica.log)

**Comment by marcelveldt** [comment]
On Android, the plugin can't do plugin itself. You can only control another spotify connect player. Simple solution: Install the spotify addon on your android box and set that device as the default in the addon's settings.

**Comment by wallon-ines** [comment]
I have a same error when trying to play album with  contextual menu (right clic and select play) but if i select track in album, working fine. 

On linux with kodi 18.5.
